"""Tests de reconciliación de roles (spec 013 US2, SC-005, [D9])."""
import pytest
from sqlalchemy import text
from sqlalchemy.exc import DBAPIError

from migration_harness import (
    DEFAULT_TENANT, LEGACY, migrated_legacy_db, require_postgres,
)

require_postgres()

DB = "basa_test_roles"


@pytest.fixture(scope="module")
def engine():
    eng = migrated_legacy_db(DB)
    yield eng
    eng.dispose()


def test_backfill_mapping(engine):
    """admin→tenant_admin; clinician/developer→client conservando la etiqueta;
    compliance_officer intacto; valor sucio → client + etiqueta original."""
    with engine.connect() as cx:
        rows = {r.username: r for r in cx.execute(text(
            "SELECT username, role, display_label FROM users"
        ))}

    assert rows["legacy-admin"].role == "tenant_admin"
    assert rows["legacy-officer"].role == "compliance_officer"
    assert rows["legacy-clinician"].role == "client"
    assert rows["legacy-clinician"].display_label == "clinician"
    assert rows["legacy-developer"].role == "client"
    assert rows["legacy-developer"].display_label == "developer"
    # Catch-all de valores legacy sucios: degrada a client, conserva la etiqueta
    assert rows["legacy-dirty"].role == "client"
    assert rows["legacy-dirty"].display_label == "hacker"


def test_super_admin_not_autogenerated(engine):
    """FR-011: la migración NO siembra super_admin (cross-tenant, solo cloud)."""
    with engine.connect() as cx:
        count = cx.execute(text(
            "SELECT COUNT(*) FROM users WHERE role = 'super_admin'"
        )).scalar()
    assert count == 0


@pytest.mark.parametrize("bad_role", ["clinician", "developer", "admin", "hacker", ""])
def test_check_rejects_out_of_enum(engine, bad_role):
    with pytest.raises(DBAPIError, match="ck_users_role"):
        with engine.begin() as cx:
            cx.execute(text(
                "UPDATE users SET role = :role WHERE username = 'legacy-officer'"
            ), {"role": bad_role})


@pytest.mark.parametrize("valid_role", ["super_admin", "tenant_admin", "compliance_officer", "client"])
def test_check_accepts_the_four_valid_roles(engine, valid_role):
    with engine.begin() as cx:
        cx.execute(text("""
            INSERT INTO users (tenant_id, username, email, password_hash, role)
            VALUES (:t, :username, :email, 'x', :role)
        """), {"t": DEFAULT_TENANT, "username": f"valid-{valid_role}",
               "email": f"valid-{valid_role}@test.test", "role": valid_role})
        cx.execute(text(
            "DELETE FROM users WHERE username = :u"), {"u": f"valid-{valid_role}"})
